version: '3.8'

services:
    app:
        build:
            context: ./app
        ports:
            - 5000:5000
        volumes:
            - ./:/app
        depends_on:
            - db          
    db:
        image: mysql:5.7
        volumes:
            - ./.dbdata:/var/lib/mysql
            - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        ports:
            - "13306:3306"
        environment:
            - MYSQL_DATABASE=todos
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=richard
            - MYSQL_PASSWORD=richard
volumes:
    .dbdata:
